### ISSUE TITLE
Problem when using two boards on one Rpi 3

### ISSUE THREAD

**Issue by MichalSeidler** [abelectronicsuk/ABElectronics_NodeJS_Libraries#1]
when i try init:
const releBus = new IoPi(0x20);

releBus stops working, when i remove line const IOBus1 = new IoPi(0x21); it works great

**Comment by abelectronicsuk** [comment]
Sorry, there was a bug with the IoPi library that caused it to fail when working with two or more boards at the same time.  I have uploaded a new version of the library as well as a new example [iopiread2boards.js](https://github.com/abelectronicsuk/ABElectronics_NodeJS_Libraries/blob/master/examples/iopi/iopiread2boards.js) which shows the best way of initialising and using two IO Pi boards together on one Raspberry Pi.
