### ISSUE TITLE
Some help in determining pwm values for servo

### ISSUE THREAD

**Issue by rikkertkoppes** [abelectronicsuk/ABElectronics_NodeJS_Libraries#2]
I do not quite understand how to pick the min and max values for the pwm. Some questions I have:

- in the [servomove demo](https://github.com/abelectronicsuk/ABElectronics_NodeJS_Libraries/blob/master/examples/servopi/servomove.js) min and max values are 250 and 500. What is the unit and range of these values?
- what is the significance of the "on" and "off" arguments of `setPWM`? I would guess it is the high time and low time in a pwm cycle, but then it seems over constrained as the frequency is also set. Also, the "on" argument is always 0 in the example

My servos should be driven at 50Hz and an impulse length between 0.9 ms and 2.1 ms. What should the min and max values be?

**Comment by abelectronicsuk** [comment]
Hi

The PWM driver uses a 12 bit value for the input so the total range is 0 to 4095.

To calculate the min and max values for your servo you first need to calculate the time in ms for each clock cycle which at 50Hz would be 20ms.  Each 20ms cycle is divided into 4095 increments so a 1ms pulse would be 4095/20=204.75 or 205 as the driver can only take integer values.

The easiest way to calculate the min and max values is to multiply your min and max times by 204.75 so you min value of 1.9ms would be 184 and the max of 2.1ms would be 430.

I have just tried measuring the values above with a logic analyser with a frequency of 50Hz and it gives a min value of  0.891ms and a max value of 2.084ms so you may just need to adjust those values slightly to get the full limits of your servo.

The on value is the time the PWM driver waits before turning the pulse on.
The off value is the duration of the pulse before turning it off plus the on value.  By using these values together you can create a pulse that has an offset from the start of the clock period so if you wanted to drive a motor which requires a series of stepped pulses you could use the on value on each channel to make the pulses start at different intervals.  For driving servos it is best to keep the on value at 0 and just use the off value to change the pulse width.

The [datasheet for the PWM driver](https://www.abelectronics.co.uk/docs/stock/raspberrypi/servopi/PCA9685.pdf) does a better job of explaining how it works.  The section on PWM control starts at page 15.
