### ISSUE TITLE
Undefined variable in the lib iopi.js

### ISSUE THREAD

**Issue by YoRab** [abelectronicsuk/ABElectronics_NodeJS_Libraries#3]
Hello,

First, thanks for the lib, it's very useful when working with the IO Pi Plus.

Nonetheless, I'd like to report a bug I faced in lib/iopi.js
I don't have any log report on hand, but the problem is quite easy to see and fix : 

l.145, in the function setPinDirection, portAdir is undefined, because a "this." is missing.
The same thing occurs l.148, with the var portBDir.

Hope it helps

**Comment by abelectronicsuk** [comment]
Hello

Thank you for finding the bug.  I have updated the iopi class with the missing "this." on portAdir and portBdir so it should be working correctly now.

**Comment by YoRab** [comment]
Great ! Thanks
