### ISSUE TITLE
Working with 'onoff' gpio library?

### ISSUE THREAD

**Issue by morphix9** [abelectronicsuk/ABElectronics_NodeJS_Libraries#4]
Would it be possible to make the extension board Pi Plus work with the 'onoff' gpio library? Onoff is way more advance, since it has interrupt detection.

**Comment by abelectronicsuk** [comment]
You could not the 'onoff' library to control the Expander Pi, or IO Pi Plus boards directly as they use the MCP23017 IC to control their IO pins where as the 'onoff' library is designed to control the Raspberry Pi GPIO pins.

You could connect the interrupt outputs, INTA and INTB, on the Expander Pi and IO Pi Plus to one of the Raspberry Pis GPIO pins via a voltage divider to drop the 5V down to 3.3V.  The boards could then be configured to trigger their interrupt pins on state change and you could use the 'onoff' library to monitor the GPIO pin for any changes.

**Comment by morphix9** [comment]
Huh, the second part was hard to understand... How can I use the GPIO pins if the IO Pi Plus is attached to all of the pin outputs on a Raspberry?

**Comment by abelectronicsuk** [comment]
The IO Pi Plus only uses the power and I2C pins, pins 1 (3.3V), 2 (5V), 3 (SDA), 5 (SCL) and 6 (GND).  All of the other GPIO pins are not connected so they are free to be used by the 'onoff' library.

**Comment by morphix9** [comment]
Perfect, thanks for letting me know. (A suggestion from a customer: some documentation or youtube video on how to get started would be perfect!)

**Comment by abelectronicsuk** [comment]
We have some tutorials on the basics of how to use the IO Pi Plus in our knowledgebase at [https://www.abelectronics.co.uk/kb/section/8/io-pi](https://www.abelectronics.co.uk/kb/section/8/io-pi)  

At the moment all of our tutorial use our [Python library](https://github.com/abelectronicsuk/ABElectronics_Python_Libraries) but the python and Node JS libraries are very similar, the main difference is the naming convension for the function names so it should be fairly easy to translate the python code to work with Node JS.

There is also a [Python example](https://github.com/abelectronicsuk/ABElectronics_Python_Libraries/blob/master/IOPi/demos/demo_iointerrupts.py) which shows how to configure the interrupts on the IO Pi Plus.

**Comment by morphix9** [comment]
What do you suggest to drop from 5V to 3.3V?

**Comment by abelectronicsuk** [comment]
The easiest way would be to use a resistor voltage divider.  We have a [voltage divider calculator](https://www.abelectronics.co.uk/tools/resistor-voltage-divider) on our website which you can use to calculate the correct values but a 10K and 18K resistor should work to drop the voltage from 5V down to 3.2V.

The other method is to use a buffer chip like the [74HC4050](https://www.nxp.com/docs/en/data-sheet/74HC4050.pdf).  The inputs on the 74HC4050 are tolerant of voltages up to 15V so you can power the chip from the Raspberry Pi 3.3V rail and it will act as a level shifter, converting the 5V down to 3.3V.  We use one of these chips on the Expander Pi as a level shifter for the SPI bus.
